# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e3ebcfab339083f83869735a219c16c062616266daaecf1911340d3aa2e33a6d79a31d2a9e54fb6d74aa999db2ac4ab29006656facfdc677b699f43332765f3

test:
  secret_key_base: 0c24e4a216e31e9dd6ec89b08e330f9951803a6aa8a424510ff0ff3b3d8d26e6265bdedfc592db74872e3c06fbe5bc7af278e083e7f27d1f43d56486d2eb94b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
